[package]
name = "scripture-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = { version = "0.10", features = ["tls"] }
tonic-health = "0.10"
prost = "0.12"
tokio = { version = "1.32", features = ["macros", "rt-multi-thread"] }
sqlx = { version = "0.9", features = ["runtime-tokio", "tls-rustls", "postgres", "uuid"] }
pgvector = { version = "0.4", features = ["sqlx"] }

[build-dependencies]
protoc-bin-vendored = "3"
tonic-build = "0.10"
