// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.31.1
// source: proto/scripture.proto

package engine

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request for processing structural text into embeddings
type EmbedTextRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Book           string                 `protobuf:"bytes,2,opt,name=book,proto3" json:"book,omitempty"`
	Chapter        int32                  `protobuf:"varint,3,opt,name=chapter,proto3" json:"chapter,omitempty"`
	Verse          int32                  `protobuf:"varint,4,opt,name=verse,proto3" json:"verse,omitempty"`
	TextContent    string                 `protobuf:"bytes,5,opt,name=text_content,json=textContent,proto3" json:"text_content,omitempty"`
	// Provider-generated vector in the database's configured embedding space.
	// The Rust service persists this value; it never fabricates a synthetic vector.
	Embedding     []float32 `protobuf:"fixed32,6,rep,packed,name=embedding,proto3" json:"embedding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedTextRequest) Reset() {
	*x = EmbedTextRequest{}
	mi := &file_proto_scripture_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedTextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedTextRequest) ProtoMessage() {}

func (x *EmbedTextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scripture_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedTextRequest.ProtoReflect.Descriptor instead.
func (*EmbedTextRequest) Descriptor() ([]byte, []int) {
	return file_proto_scripture_proto_rawDescGZIP(), []int{0}
}

func (x *EmbedTextRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *EmbedTextRequest) GetBook() string {
	if x != nil {
		return x.Book
	}
	return ""
}

func (x *EmbedTextRequest) GetChapter() int32 {
	if x != nil {
		return x.Chapter
	}
	return 0
}

func (x *EmbedTextRequest) GetVerse() int32 {
	if x != nil {
		return x.Verse
	}
	return 0
}

func (x *EmbedTextRequest) GetTextContent() string {
	if x != nil {
		return x.TextContent
	}
	return ""
}

func (x *EmbedTextRequest) GetEmbedding() []float32 {
	if x != nil {
		return x.Embedding
	}
	return nil
}

// Response detailing the vector generation success
type EmbedTextResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReferenceId   string                 `protobuf:"bytes,1,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmbedTextResponse) Reset() {
	*x = EmbedTextResponse{}
	mi := &file_proto_scripture_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmbedTextResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmbedTextResponse) ProtoMessage() {}

func (x *EmbedTextResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scripture_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmbedTextResponse.ProtoReflect.Descriptor instead.
func (*EmbedTextResponse) Descriptor() ([]byte, []int) {
	return file_proto_scripture_proto_rawDescGZIP(), []int{1}
}

func (x *EmbedTextResponse) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *EmbedTextResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EmbedTextResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

// Query for retrieving matching text via vector cosine operations
type VectorSearchRequest struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId             string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	QueryVector                []float32              `protobuf:"fixed32,2,rep,packed,name=query_vector,json=queryVector,proto3" json:"query_vector,omitempty"` // Assuming 1536 dimension size
	TopKResults                int32                  `protobuf:"varint,3,opt,name=top_k_results,json=topKResults,proto3" json:"top_k_results,omitempty"`
	MinimumSimilarityThreshold float32                `protobuf:"fixed32,4,opt,name=minimum_similarity_threshold,json=minimumSimilarityThreshold,proto3" json:"minimum_similarity_threshold,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *VectorSearchRequest) Reset() {
	*x = VectorSearchRequest{}
	mi := &file_proto_scripture_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorSearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorSearchRequest) ProtoMessage() {}

func (x *VectorSearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scripture_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorSearchRequest.ProtoReflect.Descriptor instead.
func (*VectorSearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_scripture_proto_rawDescGZIP(), []int{2}
}

func (x *VectorSearchRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *VectorSearchRequest) GetQueryVector() []float32 {
	if x != nil {
		return x.QueryVector
	}
	return nil
}

func (x *VectorSearchRequest) GetTopKResults() int32 {
	if x != nil {
		return x.TopKResults
	}
	return 0
}

func (x *VectorSearchRequest) GetMinimumSimilarityThreshold() float32 {
	if x != nil {
		return x.MinimumSimilarityThreshold
	}
	return 0
}

type VectorSearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VectorSearchResponse) Reset() {
	*x = VectorSearchResponse{}
	mi := &file_proto_scripture_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VectorSearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VectorSearchResponse) ProtoMessage() {}

func (x *VectorSearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scripture_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VectorSearchResponse.ProtoReflect.Descriptor instead.
func (*VectorSearchResponse) Descriptor() ([]byte, []int) {
	return file_proto_scripture_proto_rawDescGZIP(), []int{3}
}

func (x *VectorSearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

type SearchResult struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Book            string                 `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	Chapter         int32                  `protobuf:"varint,2,opt,name=chapter,proto3" json:"chapter,omitempty"`
	Verse           int32                  `protobuf:"varint,3,opt,name=verse,proto3" json:"verse,omitempty"`
	TextContent     string                 `protobuf:"bytes,4,opt,name=text_content,json=textContent,proto3" json:"text_content,omitempty"`
	SimilarityScore float32                `protobuf:"fixed32,5,opt,name=similarity_score,json=similarityScore,proto3" json:"similarity_score,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_proto_scripture_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_scripture_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_proto_scripture_proto_rawDescGZIP(), []int{4}
}

func (x *SearchResult) GetBook() string {
	if x != nil {
		return x.Book
	}
	return ""
}

func (x *SearchResult) GetChapter() int32 {
	if x != nil {
		return x.Chapter
	}
	return 0
}

func (x *SearchResult) GetVerse() int32 {
	if x != nil {
		return x.Verse
	}
	return 0
}

func (x *SearchResult) GetTextContent() string {
	if x != nil {
		return x.TextContent
	}
	return ""
}

func (x *SearchResult) GetSimilarityScore() float32 {
	if x != nil {
		return x.SimilarityScore
	}
	return 0
}

var File_proto_scripture_proto protoreflect.FileDescriptor

const file_proto_scripture_proto_rawDesc = "" +
	"\n" +
	"\x15proto/scripture.proto\x12\x15scriptureforge.engine\"\xc0\x01\n" +
	"\x10EmbedTextRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x12\n" +
	"\x04book\x18\x02 \x01(\tR\x04book\x12\x18\n" +
	"\achapter\x18\x03 \x01(\x05R\achapter\x12\x14\n" +
	"\x05verse\x18\x04 \x01(\x05R\x05verse\x12!\n" +
	"\ftext_content\x18\x05 \x01(\tR\vtextContent\x12\x1c\n" +
	"\tembedding\x18\x06 \x03(\x02R\tembedding\"u\n" +
	"\x11EmbedTextResponse\x12!\n" +
	"\freference_id\x18\x01 \x01(\tR\vreferenceId\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\"\xc7\x01\n" +
	"\x13VectorSearchRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12!\n" +
	"\fquery_vector\x18\x02 \x03(\x02R\vqueryVector\x12\"\n" +
	"\rtop_k_results\x18\x03 \x01(\x05R\vtopKResults\x12@\n" +
	"\x1cminimum_similarity_threshold\x18\x04 \x01(\x02R\x1aminimumSimilarityThreshold\"U\n" +
	"\x14VectorSearchResponse\x12=\n" +
	"\aresults\x18\x01 \x03(\v2#.scriptureforge.engine.SearchResultR\aresults\"\xa0\x01\n" +
	"\fSearchResult\x12\x12\n" +
	"\x04book\x18\x01 \x01(\tR\x04book\x12\x18\n" +
	"\achapter\x18\x02 \x01(\x05R\achapter\x12\x14\n" +
	"\x05verse\x18\x03 \x01(\x05R\x05verse\x12!\n" +
	"\ftext_content\x18\x04 \x01(\tR\vtextContent\x12)\n" +
	"\x10similarity_score\x18\x05 \x01(\x02R\x0fsimilarityScore2\xe7\x01\n" +
	"\x0fScriptureEngine\x12i\n" +
	"\x14ProcessTextEmbedding\x12'.scriptureforge.engine.EmbedTextRequest\x1a(.scriptureforge.engine.EmbedTextResponse\x12i\n" +
	"\x0eSearchByVector\x12*.scriptureforge.engine.VectorSearchRequest\x1a+.scriptureforge.engine.VectorSearchResponseB3Z1scriptureforge/scriptureforge/proto/engine;engineb\x06proto3"

var (
	file_proto_scripture_proto_rawDescOnce sync.Once
	file_proto_scripture_proto_rawDescData []byte
)

func file_proto_scripture_proto_rawDescGZIP() []byte {
	file_proto_scripture_proto_rawDescOnce.Do(func() {
		file_proto_scripture_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_scripture_proto_rawDesc), len(file_proto_scripture_proto_rawDesc)))
	})
	return file_proto_scripture_proto_rawDescData
}

var file_proto_scripture_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_scripture_proto_goTypes = []any{
	(*EmbedTextRequest)(nil),     // 0: scriptureforge.engine.EmbedTextRequest
	(*EmbedTextResponse)(nil),    // 1: scriptureforge.engine.EmbedTextResponse
	(*VectorSearchRequest)(nil),  // 2: scriptureforge.engine.VectorSearchRequest
	(*VectorSearchResponse)(nil), // 3: scriptureforge.engine.VectorSearchResponse
	(*SearchResult)(nil),         // 4: scriptureforge.engine.SearchResult
}
var file_proto_scripture_proto_depIdxs = []int32{
	4, // 0: scriptureforge.engine.VectorSearchResponse.results:type_name -> scriptureforge.engine.SearchResult
	0, // 1: scriptureforge.engine.ScriptureEngine.ProcessTextEmbedding:input_type -> scriptureforge.engine.EmbedTextRequest
	2, // 2: scriptureforge.engine.ScriptureEngine.SearchByVector:input_type -> scriptureforge.engine.VectorSearchRequest
	1, // 3: scriptureforge.engine.ScriptureEngine.ProcessTextEmbedding:output_type -> scriptureforge.engine.EmbedTextResponse
	3, // 4: scriptureforge.engine.ScriptureEngine.SearchByVector:output_type -> scriptureforge.engine.VectorSearchResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_scripture_proto_init() }
func file_proto_scripture_proto_init() {
	if File_proto_scripture_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_scripture_proto_rawDesc), len(file_proto_scripture_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_scripture_proto_goTypes,
		DependencyIndexes: file_proto_scripture_proto_depIdxs,
		MessageInfos:      file_proto_scripture_proto_msgTypes,
	}.Build()
	File_proto_scripture_proto = out.File
	file_proto_scripture_proto_goTypes = nil
	file_proto_scripture_proto_depIdxs = nil
}
