// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: proto/scripture.proto

package engine

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ScriptureEngine_ProcessTextEmbedding_FullMethodName = "/scriptureforge.engine.ScriptureEngine/ProcessTextEmbedding"
	ScriptureEngine_SearchByVector_FullMethodName       = "/scriptureforge.engine.ScriptureEngine/SearchByVector"
)

// ScriptureEngineClient is the client API for ScriptureEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ScriptureEngineClient interface {
	// Process text and generate embeddings
	ProcessTextEmbedding(ctx context.Context, in *EmbedTextRequest, opts ...grpc.CallOption) (*EmbedTextResponse, error)
	// Perform fast semantic vector match operations
	SearchByVector(ctx context.Context, in *VectorSearchRequest, opts ...grpc.CallOption) (*VectorSearchResponse, error)
}

type scriptureEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewScriptureEngineClient(cc grpc.ClientConnInterface) ScriptureEngineClient {
	return &scriptureEngineClient{cc}
}

func (c *scriptureEngineClient) ProcessTextEmbedding(ctx context.Context, in *EmbedTextRequest, opts ...grpc.CallOption) (*EmbedTextResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EmbedTextResponse)
	err := c.cc.Invoke(ctx, ScriptureEngine_ProcessTextEmbedding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptureEngineClient) SearchByVector(ctx context.Context, in *VectorSearchRequest, opts ...grpc.CallOption) (*VectorSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VectorSearchResponse)
	err := c.cc.Invoke(ctx, ScriptureEngine_SearchByVector_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ScriptureEngineServer is the server API for ScriptureEngine service.
// All implementations must embed UnimplementedScriptureEngineServer
// for forward compatibility.
type ScriptureEngineServer interface {
	// Process text and generate embeddings
	ProcessTextEmbedding(context.Context, *EmbedTextRequest) (*EmbedTextResponse, error)
	// Perform fast semantic vector match operations
	SearchByVector(context.Context, *VectorSearchRequest) (*VectorSearchResponse, error)
	mustEmbedUnimplementedScriptureEngineServer()
}

// UnimplementedScriptureEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedScriptureEngineServer struct{}

func (UnimplementedScriptureEngineServer) ProcessTextEmbedding(context.Context, *EmbedTextRequest) (*EmbedTextResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessTextEmbedding not implemented")
}
func (UnimplementedScriptureEngineServer) SearchByVector(context.Context, *VectorSearchRequest) (*VectorSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchByVector not implemented")
}
func (UnimplementedScriptureEngineServer) mustEmbedUnimplementedScriptureEngineServer() {}
func (UnimplementedScriptureEngineServer) testEmbeddedByValue()                         {}

// UnsafeScriptureEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ScriptureEngineServer will
// result in compilation errors.
type UnsafeScriptureEngineServer interface {
	mustEmbedUnimplementedScriptureEngineServer()
}

func RegisterScriptureEngineServer(s grpc.ServiceRegistrar, srv ScriptureEngineServer) {
	// If the following call pancis, it indicates UnimplementedScriptureEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ScriptureEngine_ServiceDesc, srv)
}

func _ScriptureEngine_ProcessTextEmbedding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmbedTextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptureEngineServer).ProcessTextEmbedding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptureEngine_ProcessTextEmbedding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptureEngineServer).ProcessTextEmbedding(ctx, req.(*EmbedTextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ScriptureEngine_SearchByVector_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VectorSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScriptureEngineServer).SearchByVector(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ScriptureEngine_SearchByVector_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScriptureEngineServer).SearchByVector(ctx, req.(*VectorSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ScriptureEngine_ServiceDesc is the grpc.ServiceDesc for ScriptureEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ScriptureEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "scriptureforge.engine.ScriptureEngine",
	HandlerType: (*ScriptureEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProcessTextEmbedding",
			Handler:    _ScriptureEngine_ProcessTextEmbedding_Handler,
		},
		{
			MethodName: "SearchByVector",
			Handler:    _ScriptureEngine_SearchByVector_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/scripture.proto",
}
