// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package engine

import (
	context "context"
	grpc "google.golang.org/grpc"
)

type ScriptureEngineClient interface {
	ProcessTextEmbedding(ctx context.Context, in *EmbedTextRequest, opts ...grpc.CallOption) (*EmbedTextResponse, error)
	SearchByVector(ctx context.Context, in *VectorSearchRequest, opts ...grpc.CallOption) (*VectorSearchResponse, error)
}

type scriptureEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewScriptureEngineClient(cc grpc.ClientConnInterface) ScriptureEngineClient {
	return &scriptureEngineClient{cc}
}

func (c *scriptureEngineClient) ProcessTextEmbedding(ctx context.Context, in *EmbedTextRequest, opts ...grpc.CallOption) (*EmbedTextResponse, error) {
	out := new(EmbedTextResponse)
	err := c.cc.Invoke(ctx, "/scriptureforge.engine.ScriptureEngine/ProcessTextEmbedding", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scriptureEngineClient) SearchByVector(ctx context.Context, in *VectorSearchRequest, opts ...grpc.CallOption) (*VectorSearchResponse, error) {
	out := new(VectorSearchResponse)
	err := c.cc.Invoke(ctx, "/scriptureforge.engine.ScriptureEngine/SearchByVector", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

type EmbedTextRequest struct {
	OrganizationId string `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	Book           string `protobuf:"bytes,2,opt,name=book,proto3" json:"book,omitempty"`
	Chapter        int32  `protobuf:"varint,3,opt,name=chapter,proto3" json:"chapter,omitempty"`
	Verse          int32  `protobuf:"varint,4,opt,name=verse,proto3" json:"verse,omitempty"`
	TextContent    string `protobuf:"bytes,5,opt,name=text_content,json=textContent,proto3" json:"text_content,omitempty"`
}

type EmbedTextResponse struct {
	ReferenceId  string `protobuf:"bytes,1,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	Success      bool   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage string `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
}

type VectorSearchRequest struct {
	OrganizationId             string    `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	QueryVector                []float32 `protobuf:"fixed32,2,rep,packed,name=query_vector,json=queryVector,proto3" json:"query_vector,omitempty"`
	TopKResults                int32     `protobuf:"varint,3,opt,name=top_k_results,json=topKResults,proto3" json:"top_k_results,omitempty"`
	MinimumSimilarityThreshold float32   `protobuf:"fixed32,4,opt,name=minimum_similarity_threshold,json=minimumSimilarityThreshold,proto3" json:"minimum_similarity_threshold,omitempty"`
}

type VectorSearchResponse struct {
	Results []*SearchResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
}

type SearchResult struct {
	Book            string  `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	Chapter         int32   `protobuf:"varint,2,opt,name=chapter,proto3" json:"chapter,omitempty"`
	Verse           int32   `protobuf:"varint,3,opt,name=verse,proto3" json:"verse,omitempty"`
	TextContent     string  `protobuf:"bytes,4,opt,name=text_content,json=textContent,proto3" json:"text_content,omitempty"`
	SimilarityScore float32 `protobuf:"fixed32,5,opt,name=similarity_score,json=similarityScore,proto3" json:"similarity_score,omitempty"`
}
